# Generated by Django 5.2 on 2025-05-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("skills", models.TextField(blank=True, null=True)),
                ("date_posted", models.CharField(max_length=100)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
